### PR TITLE
[add] make slack team an environment variable

### PR DESCRIPTION
**Pull request by simon0191**
Make SLACK_TEAM an environment variable so you can use/test leonel with different slack teams.

### CODE REVIEW

**Comment by buritica** [comment]
great, sorry for the wait I was on vacation. It should probably error if it's not set, no?

**Comment by simon0191** [comment]
I use colombia-dev as default: `let teamName = process.env.SLACK_TEAM_NAME || 'colombia-dev';`. But I can check for required env variables and close #6 if you want

**Comment by buritica** [comment]
That would be a great help @simon0191 !

**Comment by simon0191** [comment]
Have a look @buritica (I'll have limited internet access from tomorrow until June 9th, sorry if I can't answer immediately)

**Comment by buritica** [comment]
This looks great, can you add your name to the contributors list in the package.json? I'll merge after that, thanks again!

**Comment by simon0191** [comment]
done :)

**Pull request merged**
